### ISSUE TITLE
Fetch doesn't return empty cells

### ISSUE THREAD

**Issue by iamchristopher** [samcday/node-google-spreadsheets#24]
I'm not sure if this is a limitation of Google's API, or if this is specifically implemented in this package, but fetching a spreadsheet doesn't include empty cells.

So given a spreadsheet with an empty cell in the second row:

Heading 1 | Heading 2 | Heading 3
---|---|---
Cell 1 | | Cell 3

You get this response (headings removed):

```
{
    // Headings removed

    '1': {
        row: '2',
        col: '1',
        value: 'Cell 1'
    },
    '3': {
        row: '2',
        col: '3',
        value: 'Cell 3'
    }
}
```

Normally this wouldn't be an issue, but a project I'm working on has a requirement to report on empty cells. Is there a way around this I'm not aware of?

**Comment by samcday** [comment]
I think this is working as intended. Given that a spreadsheet can have a value in A1 and then a value in A99999999999999 (or whatever the actual limit of a spreadsheet is ;P), you wouldn't want the API returning all those empty cells.

You should be able to easily approximate this behaviour yourself though. For each row, find the lowest and highest column numbers, then iterate over the full domain of values between those constraints, and check for cells for each co-ordinate that have no value specified.

**Comment by iamchristopher** [comment]
Unless you're missing cells at the start or end of the row.

Anyway, I've since found a solution that works ok for my project. Thanks for responding.
