### ISSUE TITLE
CORS issue with redirect URL

### ISSUE THREAD

**Issue by mrvamsidhar** [samcday/node-google-spreadsheets#26]
Hi, First of all Thanks for sharing this module. I am currently writing and Nodejs/Angular application to read data from spreadsheet and display data to user. In the process I am using this module to read google spreadsheet using OAUTH2. I am having CORS issue on return from REDIRECT URL (callback url).
XMLHttpRequest cannot load https://accounts.google.com/o/oauth2/auth?access_type=offline&scope=https%3…t.com&redirect_uri=http%3A%2F%2Flocalhost%3A1337%2Ferrors%2Foauth2callback. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:1337' is therefore not allowed access.

All I am doing is like below: Here is how my node module looks like:
var scopes = [
   "https://spreadsheets.google.com/feeds/"
];
var authUrl = oauth2Client.generateAuthUrl({
    access_type: 'online', // 'online' (default) or 'offline' (gets refresh_token)
    scope: scopes // If you only need one scope you can pass it as string
});
router.get('/', function (req, res) {
    console.log('Redirecting to URL: ' + JSON.stringify(authUrl));
    res.redirect(authUrl);
});
router.get('/oauth2callback', function(req, res) {
    console.log('Got code: ', (req.query.code));
     oauth2Client.getToken(req.query.code, function (err, tokens) {
        // Now tokens contains an access_token and an optional refresh_token. Save them.
        if (!err) {
            oauth2Client.setCredentials(tokens);
            // Assuming you already obtained an OAuth2 token that has access to the correct scopes somehow... 
            GoogleSpreadsheet({
                key: '1vj5LdGYvxIjm7HIBFi1V44cqddd36Pxz0bu9xv1YvtysVg',
                auth: oauth2Client
            }, function(eror, spreadsheet) {
                var worksheet = spreadsheet.worksheets[0];
                console.log('** worksheets - ', worksheet);
                worksheet.rows({
                    key: '1vj5LdGYvxIjm7HIBFi1V44cqddd36Pxz0bu9xv1YvtysVg',
                    worksheet: worksheet.id
                },function(error,rows) {
                   // console.log('** rows - ', rows);
                     res.send({
                        length:rows.length,
                        rows:rows
                    });                 

                });
            });
        } else {
            res.sendStatus(500);
        }
    });
    res.sendStatus(500);
});

From my Angular JS controller, I am calling above get method and facing CORS issue. Can you let me know what the issue is?

**Comment by mrvamsidhar** [comment]
any update on this please?

**Comment by mrvamsidhar** [comment]
Any update on this please?

**Comment by samcday** [comment]
Hey there! Sorry for the slow reply on this issue. I'm not actually sure what the issue is here. That said, I designed this library to not care about auth specifically so I didn't have to own that domain of problems :) It sounds like this issue would be better off raised with the oauth2 library you're using. Adding CORS header to your server is a pretty straightforward thing to do generally though, if you use a package like [cors](https://www.npmjs.com/package/cors)
