### ISSUE TITLE
How can I search a column for specific data?

### ISSUE THREAD

**Issue by sirshurf** [samcday/node-google-spreadsheets#27]

**Comment by samcday** [comment]
@sirshurf I'm not sure if this is something that the Google Spreadsheets API provides. If you find anything let me know though, and I'll be sure to surface that functionality in this library's API.

At any rate, a DIY approach here should be pretty straightforward. You'd request chunks of the spreadsheet (if it's large) using [GoogleSpreadsheets.rows()](https://github.com/samcday/node-google-spreadsheets#googlespreadsheetsrowsopts-callback), then iterate through the results and drop any rows whose columns don't match your criteria.
