### ISSUE TITLE
What's up with the $t business?

### ISSUE THREAD

**Issue by optikalefx** [samcday/node-google-spreadsheets#29]
When I ask for a row, I get some odd things. Namely 1) and ID, 2) a "content" object and 3) empty things are $t

```
{ id: { '$t': 'https://spreadsheets.google.com/feeds/list/1TQZjoAF15aSnXwZlQ_l71H9WqwCJBPDEy6i1tDUa2UY/o3l1e6y/public/values/cpzh4' },
  updated: '2015-09-16T19:42:40.798Z',
  title: { '$t': '' },
  content: 'question: Name this president., answer: George Washington, clarification: 1st President, 1789-1797, imageurl: https://dl.dropboxusercontent.com/s/et8jay2by28taq7/geowash.jpg?dl=0',
  types: { '$t': '' },
```

The expected output would be

```
{
    updated: '2015-09-16T19:42:40.798Z',
    title: '',
    types: ''
}
```

Any idea why all that extra fluff is added?

**Comment by optikalefx** [comment]
I added this block to normalize these. I feel like your lib should do this automatically on a `rows` call.

``` js
rows.forEach(function(row) {
	delete row.id;
	delete row.content;
	for(let k in row) {
		if( typeof row[k] === 'object') {
			row[k] = '';
		}
	}
});
```

**Comment by samcday** [comment]
This lib is a fairly lightweight wrapper around the Google [Sheets API](https://developers.google.com/google-apps/spreadsheets/?hl=en). A lot of this weirdness is simply what comes back from the API :)

**Comment by optikalefx** [comment]
you should have an option passed in (that is default) for normalizing. It's not so useful when the data you get back is weird. I get the lightweight part but that means every developer that uses this lib has to repeat extra effort.

**Comment by samcday** [comment]
@optikalefx Sounds reasonable, happy to merge a PR if you come up with one :)
