### ISSUE TITLE
How do you get the worksheet ID?

### ISSUE THREAD

**Issue by optikalefx** [samcday/node-google-spreadsheets#30]
The URL doesn't seem to have the worksheet ID, so I'm forced to get all worksheets and filter by title. Any options there?

**Comment by samcday** [comment]
@optikalefx Every spreadsheet I can find in my Google Drive has a long worksheet ID in the URL. If this is still an issue for you, can you provide some example URLs that don't have a worksheet ID?

**Comment by optikalefx** [comment]
Example of one of my sheets

https://docs.google.com/spreadsheets/d/1TQZjoAF15aSnXwZlQ_l71H9WqwCJBPDEy6i1tDUa2UY/edit#gid=361901701

Example of another worksheet in that same document
https://docs.google.com/spreadsheets/d/1TQZjoAF15aSnXwZlQ_l71H9WqwCJBPDEy6i1tDUa2UY/edit#gid=1386336754

The "gid" is changing at the end there but that isn't the ID of the sheet. Or doesn't work in the tool.

This is the only way I could get it to work for me

```
let rows = yield new Promise( (resolve) => {
	GoogleSpreadsheets({
		key: '1TQZjoAF15aSnXwZlQ_l71H9WqwCJBPDEy6i1tDUa2UY'
	}, (err, spreadsheet) => {
		let worksheet = _.find(spreadsheet.worksheets, {
			title: sheet
		});
		worksheet.rows({}, (err, rows) => {

			// normalize the rows
			rows.forEach( (row) => {
```

Where `sheet` is the text name of the sheet. The one that you see in the tab at the bottom.

**Comment by optikalefx** [comment]
Also, when I `console.log` the spreadsheet I get this http://cl.ly/image/2d0B070x1E2C. And you can see the ID there is alphanumeric. But the `gid` found in the URLs above are all numeric. They are not the ids that your thing is looking for.

**Comment by samcday** [comment]
Ah right, I get you now. The main spreadsheet key is the alphanumeric one, but then loading a specific worksheet isn't ideal. You have to iterate through `spreadsheet.worksheets` and find the one you want by title, as you say.

If you have any suggestions for how this could be improved, let me know! Better yet, raise a PR :)

**Comment by fabform** [comment]
This is handy to find the google sheet id
[how to find google sheet id](https://fabform.io/a/how-to-find-google-sheet-id)
