### ISSUE TITLE
rows() removes the casing of keys

### ISSUE THREAD

**Issue by optikalefx** [samcday/node-google-spreadsheets#31]
All my keys have their casing removed. I get keys like `useonlywronganswerpool` instead of useOnlyWrongAnswerPool.  This is important because once these go to my database, i can't trust the column headers to match my expected field types.

Does google do this or is this a bug somewhere?

Thanks!

**Comment by optikalefx** [comment]
It looks like this is coming from google. For now, I'll add a auto-camelcasing function for my headers, but this should be added as a disclaimer to the readme.

**Comment by samcday** [comment]
@optikalefx thanks for raising this issue. Feel free to raise a PR that makes the README changes you think are necessary :)
