### ISSUE TITLE
Support googleapis 2.x

### ISSUE THREAD

**Issue by traviscrawford** [samcday/node-google-spreadsheets#36]
In [spreadsheets.js](https://github.com/samcday/node-google-spreadsheets/blob/master/lib/spreadsheets.js) we see a check for the `googleapis` dependency version, explicitly checking for a 1.x series version.

The 2.x series of [googleapis](https://www.npmjs.com/package/googleapis) has been available since March. I've used:

    "google-spreadsheets": "0.4.2",
    "googleapis": "2.0.4",

together and AFAICT it works. What do you think about updating the check to support 2.x series googleapis?

**Comment by samcday** [comment]
You're right - `googleapis`@2 works fine. I've written a test to validate that and I've just published version `0.5.0` of the library that no longer complains about the newer version of `googleapis`.

Thanks a lot! :)

**Comment by traviscrawford** [comment]
Thanks for updating this! We just upgraded and have not noticed any issues.
