### ISSUE TITLE
Browser issues: size and setting headers

### ISSUE THREAD

**Issue by arve0** [samcday/node-google-spreadsheets#37]
Hi again!
I've been playing around with reducing the size of the browser build. When using [browser-request](https://github.com/iriscouch/browser-request) and [statuses](https://github.com/jshttp/statuses), the size drops from ~1MB to ~40kB.

Building with browser-request is as simple as adding `browser: { 'request': 'browser-request'}` to package.json. Using statuses will replace `http.STATUS_CODES[code]` with `statuses[code]`, and the extra "burden" of another dependency. What do you think of a PR?

At the same time, I found out that [this commit](https://github.com/samcday/node-google-spreadsheets/commit/c86826374302fa17370653e4bca1f9d2ae7bb9da) broke the browser build (line 35 in spreadsheets.js). Setting headers in browser will force an "OPTIONS" request. Which fails, as [google does not set Access-Control-Allow-Origin on OPTIONS requests](http://stackoverflow.com/questions/28546969/cors-authorization-on-google-sheets-api-requests).

**Comment by samcday** [comment]
Heya! A PR to reduce the weight is definitely welcome! Submit away :)

As for the CORS problem - any ideas how we could fix that?

**Comment by samcday** [comment]
Just pushed up a commit that should help with the CORS issue - [docs](https://developers.google.com/google-apps/spreadsheets/authorize) suggest you can pass `?v=3.0` instead of using the `GData-Version` header.
