### ISSUE TITLE
WARN: google-spreadsheets detected googleapis@XX is installed. This version is unrecognised by this version of google-spreadsheets and may not work correctly.

### ISSUE THREAD

**Issue by colomboTgs** [samcday/node-google-spreadsheets#47]
Hi, I get this warning as the module is checking for googleapis versions 1.X and 2.X

[Link to Code](https://github.com/samcday/node-google-spreadsheets/blob/dcf7807417a23d643bb8e324066de2fec2b10f59/lib/spreadsheets.js#L12)

The latest published version right now has a dependency on version 20.1.0 googleapis": "^20.1.0" so even the tests spit this warning. Am I missing something. Right now I'm using v27.0.0 of the googleapis and tests are passing. Can you update this? Should I do a PR? 

Thanks.

**Comment by colomboTgs** [comment]
I'm sorry I think I rushed a bit there. There are some changes in the google-api-nodejs-client for version 25 that would break the module specifically [this](https://github.com/samcday/node-google-spreadsheets/blob/dcf7807417a23d643bb8e324066de2fec2b10f59/lib/spreadsheets.js#L85) because as you can see in the Request to Axios  [here](https://github.com/google/google-api-nodejs-client/releases) there is a change in parameters for requests.

```
//OLD CODE
oAuth2Client.request({
  uri: 'https://www.googleapis.com/plus/v1/people?query=pizza'
}, function (err, body, res) {
  console.log('The body of the response was ' + body);
});

// NEW CODE (using callbacks)
oAuth2Client.request({
  // note that we're using `url` instead of `uri` here, per the Axios request config.
  url: 'https://www.googleapis.com/plus/v1/people?query=pizza'
}, function (err, res) {
  // The body isn't returned as part of the callback, and is available from `res.data`
  console.log(`The body of the response was ${res.data}`);
});

```

**Comment by dpogue** [comment]
I have an open PR (#46) to update to the newer google-api-nodejs-client and also bump the version on that warning message

**Comment by samcday** [comment]
[`2.0.0`](https://www.npmjs.com/package/google-spreadsheets/v/2.0.0) is now published addressing this issue. Many thanks for @dpogue for tackling this.
